export const accountsData = {
    keys: [
        "code",
        "client",
        "region",
        "site",
        "building",
        "company",
        "number",
        "account_type",
        "status",
        "rate",
        "description",
        "created_at",
        "updated_at"
    ],
    config: {
        client: {
            isVisible: true,
            label: "Client",
            class: "reg-code",
            searchKey: "clients.name",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "clients",
            commonSearchKey: "clients",
            commonSearchObjectKey: "name"
        },
        account_type: {
            isVisible: true,
            label: "Account Type",
            class: "reg-code",
            searchKey: "accounts.account_type",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "accounts",
            commonSearchKey: "accounts",
            commonSearchObjectKey: "account_type"
        },
        building: {
            isVisible: true,
            label: "Building",
            class: "reg-code",
            searchKey: "buildings.name",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "buildings.name",
            commonSearchKey: "buildings",
            commonSearchObjectKey: "name"
        },
        building_sf: {
            isVisible: true,
            label: "Building SF",
            class: "",
            searchKey: "accounts.building_sf",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "accounts",
            commonSearchKey: "accounts",
            commonSearchObjectKey: "building_sf"
        },
        region: {
            isVisible: true,
            label: "Region",
            class: "reg-code",
            searchKey: "regions.name",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "regions",
            commonSearchKey: "regions",
            commonSearchObjectKey: "name"
        },
        site: {
            isVisible: true,
            label: "Site",
            class: "reg-code",
            searchKey: "sites.name",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "sites",
            commonSearchKey: "sites",
            commonSearchObjectKey: "name"
        },
        number: {
            isVisible: true,
            label: "Account Number",
            class: "reg-code",
            searchKey: "accounts.number",
            type: "number",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "accounts",
            commonSearchKey: "accounts",
            commonSearchObjectKey: "number"
        },
        status: {
            isVisible: true,
            label: "Status",
            class: "reg-code",
            searchKey: "accounts.status",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "accounts",
            commonSearchKey: "accounts",
            commonSearchObjectKey: "status"
        },
        description: {
            isVisible: true,
            label: "Description",
            class: "",
            searchKey: "accounts.description",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "accounts",
            commonSearchKey: "accounts",
            commonSearchObjectKey: "description"
        },
        code: {
            isVisible: true,
            label: "Code",
            class: "reg-code",
            searchKey: "accounts.code",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "accounts",
            commonSearchKey: "accounts",
            commonSearchObjectKey: "code"
        },
        rate: {
            isVisible: true,
            label: "Rate",
            class: "reg-code",
            searchKey: "accounts.rate",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "accounts",
            commonSearchKey: "accounts",
            commonSearchObjectKey: "rate"
        },
        company: {
            isVisible: true,
            label: "Company",
            class: "",
            searchKey: "accounts.company",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "accounts",
            commonSearchKey: "accounts",
            commonSearchObjectKey: "company"
        },
        created_at: {
            isVisible: true,
            label: "Created At",
            class: "",
            searchKey: "accounts.created_at",
            type: "date",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "created_at",
            commonSearchKey: "created_at",
            commonSearchObjectKey: "created_at"
        },
        updated_at: {
            isVisible: true,
            label: "Updated At",
            class: "",
            searchKey: "accounts.updated_at",
            type: "date",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "updated_at",
            commonSearchKey: "updated_at",
            commonSearchObjectKey: "updated_at"
        }
    },
    data: []
};
