export const electricTableData = {
    keys: [
        "client",
        "region",
        "site",
        "building",
        "account",
        "account_description",
        "meter",
        "meter_description",
        "meter_type",
        "year",
        "month",
        "kwh_usage",
        "mmbtu_usage",
        "kw_usage",
        "kwh_cost",
        "kw_cost",
        "total_electric_cost",
        "billing_days",
        "meter_read",
        "created_at",
        "updated_at"
    ],
    config: {
        client: {
            isVisible: false,
            label: "Client",
            class: "width-220px",
            searchKey: "clients.name",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "client",
            commonSearchKey: "",
            commonSearchObjectKey: ""
        },
        account: {
            isVisible: true,
            label: "Account",
            class: "reg-code",
            searchKey: "accounts.number",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "accounts",
            commonSearchKey: "accounts",
            commonSearchObjectKey: "number"
        },
        account_description: {
            isVisible: false,
            label: "Account Description",
            class: "width-220px",
            searchKey: "accounts.description",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "accounts",
            commonSearchKey: "accounts",
            commonSearchObjectKey: "description"
        },
        region: {
            isVisible: true,
            label: "Region",
            class: "reg-code",
            searchKey: "regions.name",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "regions",
            commonSearchKey: "regions",
            commonSearchObjectKey: "name"
        },
        site: {
            isVisible: true,
            label: "Site",
            class: "reg-code",
            searchKey: "sites.name",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "sites",
            commonSearchKey: "sites",
            commonSearchObjectKey: "name"
        },
        building: {
            isVisible: true,
            label: "Building",
            class: "reg-code",
            searchKey: "buildings.name",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "buildings.name",
            commonSearchKey: "buildings",
            commonSearchObjectKey: "name"
        },
        meter: {
            isVisible: true,
            label: "Meter",
            class: "reg-code",
            searchKey: "meters.meter",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "meters.meter",
            commonSearchKey: "meters",
            commonSearchObjectKey: "meter"
        },
        meter_description: {
            isVisible: false,
            label: "Meter Description",
            class: "width-220px",
            searchKey: "meters.description",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "meters.description",
            commonSearchKey: "meters",
            commonSearchObjectKey: "meter"
        },
        meter_type: {
            isVisible: false,
            label: "Meter Type",
            class: "reg-code",
            searchKey: "meter_readings.meter_type",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "meter_type",
            commonSearchKey: "meter_type",
            commonSearchObjectKey: "meter_type"
        },
        meter_read: {
            isVisible: true,
            label: "Meter Read",
            class: "reg-code",
            searchKey: "meter_readings.meter_read",
            type: "date",
            hasWildCardSearch: false,
            hasCommonSearch: false,
            getListTable: "meter_read",
            commonSearchKey: "meter_read",
            commonSearchObjectKey: "meter_read"
        },
        billing_days: {
            isVisible: true,
            label: "Billing Days",
            class: "custom-tablewidth-small",
            searchKey: "meter_readings.billing_days",
            type: "number",
            hasWildCardSearch: false,
            hasCommonSearch: false,
            getListTable: "billing_days",
            commonSearchKey: "billing_days",
            commonSearchObjectKey: "billing_days"
        },
        month: {
            isVisible: true,
            label: "Month",
            class: "custom-tablewidth-small",
            searchKey: "meter_readings.month",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "month",
            commonSearchKey: "meter_readings",
            commonSearchObjectKey: "month"
        },
        year: {
            isVisible: true,
            label: "Year",
            class: "custom-tablewidth-small",
            searchKey: "meter_readings.year",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "year",
            commonSearchKey: "meter_readings",
            commonSearchObjectKey: "year"
        },
        kw_cost: {
            isVisible: true,
            label: "KW Cost ($)",
            class: "custom-tablewidth-small",
            searchKey: "meter_readings.kw_cost",
            type: "number",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "kw_cost",
            commonSearchKey: "kw_cost",
            commonSearchObjectKey: "kw_cost"
        },
        kw_usage: {
            isVisible: true,
            label: "KW Demand",
            class: "custom-tablewidth-small",
            searchKey: "meter_readings.kw_usage",
            type: "number",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "kw_usage",
            commonSearchKey: "kw_usage",
            commonSearchObjectKey: "kw_usage"
        },
        kwh_cost: {
            isVisible: true,
            label: "kWh Cost ($)",
            class: "reg-code",
            searchKey: "meter_readings.kwh_cost",
            type: "number",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "kwh_cost",
            commonSearchKey: "kwh_cost",
            commonSearchObjectKey: "kwh_cost"
        },
        kwh_usage: {
            isVisible: true,
            label: "kWh Usage",
            class: "reg-code",
            searchKey: "meter_readings.kwh_usage",
            type: "number",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "kwh_usage",
            commonSearchKey: "kwh_usage",
            commonSearchObjectKey: "kwh_usage"
        },

        created_at: {
            isVisible: true,
            label: "Created At",
            class: "readings.created_at",
            searchKey: "meter_readings.created_at",
            type: "date",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "regions",
            commonSearchKey: "regions",
            commonSearchObjectKey: "created_at"
        },
        updated_at: {
            isVisible: true,
            label: "Updated At",
            class: "",
            searchKey: "meter_readings.updated_at",
            type: "date",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "updated_at",
            commonSearchKey: "updated_at",
            commonSearchObjectKey: "updated_at"
        },
        mmbtu_usage: {
            isVisible: true,
            label: "MMBTU Usage",
            class: "custom-tablewidth-small",
            searchKey: "meter_readings.mmbtu_usage",
            type: "number",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "mmbtu_usage",
            commonSearchKey: "mmbtu_usage",
            commonSearchObjectKey: "mmbtu_usage"
        },
        total_electric_cost: {
            isVisible: true,
            label: "Total Electric Cost ($)",
            class: "reg-code",
            searchKey: "meter_readings.total_electric_cost",
            type: "number",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "regions",
            commonSearchKey: "regions",
            commonSearchObjectKey: "total_electric_cost"
        }
    },
    data: []
};
