export const meterTemplateTableData = {
    keys: [
        "code",
        "client",
        "region",
        "site",
        "building",
        "account",
        "account_type",
        "account_description",
        "meter",
        "meter_type",
        "description",
        "created_at",
        "updated_at"
    ],
    config: {
        code: {
            isVisible: true,
            label: "Code",
            class: "reg-code",
            searchKey: "meters.code",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "meters",
            commonSearchKey: "meters",
            commonSearchObjectKey: "code"
        },
        account: {
            isVisible: true,
            label: "Account",
            class: "reg-code",
            searchKey: "accounts.code",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "account",
            commonSearchKey: "accounts",
            commonSearchObjectKey: "code"
        },
        account_type: {
            isVisible: false,
            label: "Account Type",
            class: "reg-code",
            searchKey: "accounts.account_type",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "accounts",
            commonSearchKey: "accounts",
            commonSearchObjectKey: "account_type"
        },
        account_description: {
            isVisible: false,
            label: "Account Description",
            class: "reg-code",
            searchKey: "accounts.description",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "accounts",
            commonSearchKey: "accounts",
            commonSearchObjectKey: "description"
        },
        client: {
            isVisible: true,
            label: "Client",
            class: "reg-code",
            searchKey: "clients.name",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "clients",
            commonSearchKey: "clients",
            commonSearchObjectKey: "name"
        },
        region: {
            isVisible: true,
            label: "Region",
            class: "reg-code",
            searchKey: "regions.name",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "regions",
            commonSearchKey: "regions",
            commonSearchObjectKey: "name"
        },
        site: {
            isVisible: true,
            label: "Site",
            class: "reg-code",
            searchKey: "sites.name",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "sites",
            commonSearchKey: "sites",
            commonSearchObjectKey: "name"
        },
        building: {
            isVisible: true,
            label: "Building",
            class: "reg-code",
            searchKey: "buildings.name",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "buildings.name",
            commonSearchKey: "buildings",
            commonSearchObjectKey: "name"
        },
        meter: {
            isVisible: true,
            label: "Meter",
            class: "reg-code",
            searchKey: "meters.meter",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "meters",
            commonSearchKey: "meters",
            commonSearchObjectKey: "meter"
        },
        meter_type: {
            isVisible: true,
            label: "Type",
            class: "reg-code",
            searchKey: "meters.meter_type",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: true,
            getListTable: "meters",
            commonSearchKey: "meters",
            commonSearchObjectKey: "meter_type"
        },
        description: {
            isVisible: true,
            label: "Description",
            class: "",
            searchKey: "meters.description",
            type: "string",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "meters",
            commonSearchKey: "meters",
            commonSearchObjectKey: "description"
        },
        created_at: {
            isVisible: true,
            label: "Created At",
            class: "",
            searchKey: "meters.created_at",
            type: "date",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "created_at",
            commonSearchKey: "created_at",
            commonSearchObjectKey: "created_at"
        },
        updated_at: {
            isVisible: true,
            label: "Updated At",
            class: "",
            searchKey: "meters.updated_at",
            type: "date",
            hasWildCardSearch: true,
            hasCommonSearch: false,
            getListTable: "updated_at",
            commonSearchKey: "updated_at",
            commonSearchObjectKey: "updated_at"
        }
    },
    data: []
};
