// //Update  Entity Param
export const UPDATE_ASSET_MANAGEMENT_ENTITY_PARAMS_SUCCESS = "UPDATE_ASSET_MANAGEMENT_ENTITY_PARAMS_SUCCESS";
export const UPDATE_ASSET_MANAGEMENT_ENTITY_PARAMS_FAILURE = "UPDATE_ASSET_MANAGEMENT_ENTITY_PARAMS_FAILURE";

// Get chart data
export const GET_CHARTS_DETAILS_REQUEST = "GET_CHARTS_DETAILS_REQUEST";
export const GET_CHARTS_DETAILS_SUCCESS = "GET_CHARTS_DETAILS_SUCCESS";
export const GET_CHARTS_DETAILS_FAILURE = "GET_CHARTS_DETAILS_FAILURE";

export const GET_FILTER_LISTS_REQUEST = "GET_CHART_MASTER_FILTER_LISTS_REQUEST";
export const GET_FILTER_LISTS_SUCCESS = "GET_CHART_MASTER_FILTER_LISTS_SUCCESS";
export const GET_FILTER_LISTS_FAILURE = "GET_CHART_MASTER_FILTER_LISTS_FAILURE";

export const SAVE_CHART_POPUP = "SAVE_CHART_POPUP";
export const SAVE_CHART_VIEW = "SAVE_CHART_VIEW";
export const SAVE_CHART_TAB = "SAVE_CHART_TAB";
export const SAVE_CHART_PARAMS = "SAVE_CHART_PARAMS";
export const SAVE_SELECTED_MASTER_FILTER_LIST = "SAVE_SELECTED_MASTER_FILTER_LIST";
//get fcicharts
export const GET_SFCI_CHART_REQUEST = "GET_SFCI_CHART_REQUEST";
export const GET_SFCI_CHART_SUCCESS = "GET_SFCI_CHART_SUCCESS";
export const GET_SFCI_CHART_FAILURE = "GET_SFCI_CHART_FAILURE";
//Get SFCI chart Data
