// Get all regions
export const GET_MENU_ITEMS_REQUEST = "GET_MENU_ITEMS_REQUEST";
export const GET_MENU_ITEMS_SUCCESS = "GET_MENU_ITEMS_SUCCESS";
export const GET_MENU_ITEMS_FAILURE = "GET_MENU_ITEMS_FAILURE";

export const GET_PROJECT_MENU_ITEMS_REQUEST = "GET_PROJECT_MENU_ITEMS_REQUEST";
export const GET_PROJECT_MENU_ITEMS_SUCCESS = "GET_PROJECT_MENU_ITEMS_SUCCESS";
export const GET_PROJECT_MENU_ITEMS_FAILURE = "GET_PROJECT_MENU_ITEMS_FAILURE";

// Set form dirty (for detect unsaved changes)
export const SET_FORM_DIRTY_SUCCESS = "SET_FORM_DIRTY_SUCCESS";
export const SET_FORM_DIRTY_FAILURE = "SET_FORM_DIRTY_FAILURE";

export const GET_MENU_LINK_EMAIL_REQUEST = "GET_MENU_LINK_EMAIL_REQUEST";
export const GET_MENU_LINK_EMAIL_SUCCESS = "GET_MENU_LINK_EMAIL_SUCCESS";
export const GET_MENU_LINK_EMAIL_FAILURE = "GET_MENU_LINK_EMAIL_FAILURE";

export const entities = {
    RECOMMENDATIONS: "RECOMMENDATIONS",
    NARRATIVES: "NARRATIVES",
    ASSET_MANAGEMENT: "ASSET_MANAGEMENT",
    SMART_CHARTS: "SMART_CHARTS"
};

export const LOCK_STATUS = {
    LOCKED: "locked",
    NOT_LOCKED: "not_locked",
    PARTIALLY_LOCKED: "partially_locked"
};

export const FILE_TYPE = {
    WORD: "word",
    PDF: "pdf",
    PPT: "ppt"
};